------ MODULE AST -------
EXTENDS TLC
fairness == ""
 
ast == 
[type     |-> "uniprocess", 
 name  |-> "QueensPluscal", 
 decls  |-> <<[var |-> "todo", eqOrIn |-> "=", val |-> << "{", "<<", ">>", "}" >>], 
              [var |-> "sols", eqOrIn |-> "=", val |-> << "{", "}" >>], 
              [var |-> "pgo_read", eqOrIn |-> "=", val |-> << "[ << var, lab >> \in {"todo", "sols"} \X {"nxtQ"} |-> 0 ]" >>], 
              [var |-> "pgo_write", eqOrIn |-> "=", val |-> << "[ << var, lab >> \in {"todo", "sols"} \X {"nxtQ"} |-> 0 ]" >>]>>,
 defs   |-> <<  >>,
 prcds  |-> <<>>,
 body  |-> <<[label |-> "nxtQ",
              stmts |-> <<[type    |-> "while", 
                           test    |-> << "todo", "#", "{", "}" >>,
                           labDo   |-> <<[label |-> "pgo_nxtQ",
                                          stmts |-> <<[type |-> "assignment",
                                                       ass  |-> <<[lhs |-> [var |-> "pgo_read", sub |-> << "[ "todo", "nxtQ" ]" >>],
                                                                   rhs |-> << "pgo_read[ "todo", "nxtQ" ] - 1" >>], 
                                                                  [lhs |-> [var |-> "pgo_read", sub |-> << "[ "sols", "nxtQ" ]" >>],
                                                                   rhs |-> << "pgo_read[ "sols", "nxtQ" ] - 1" >>]>>], 
                                                      [type |-> "assignment",
                                                       ass  |-> <<[lhs |-> [var |-> "pgo_write", sub |-> << "[ "todo", "nxtQ" ]" >>],
                                                                   rhs |-> << "pgo_write[ "todo", "nxtQ" ] - 1" >>], 
                                                                  [lhs |-> [var |-> "pgo_write", sub |-> << "[ "sols", "nxtQ" ]" >>],
                                                                   rhs |-> << "pgo_write[ "sols", "nxtQ" ] - 1" >>]>>]>>]>>,
                           unlabDo |-> <<[type   |-> "with", 
                                          var    |-> "queens",
                                          eqOrIn |-> "\\in",
                                          exp    |-> << "todo" >>,
                                          do     |-> <<[type   |-> "with", 
                                                        var    |-> "nxtQ",
                                                        eqOrIn |-> "=",
                                                        exp    |-> << "Len", "(", "queens", ")", "+", "1" >>,
                                                        do     |-> <<[type   |-> "with", 
                                                                      var    |-> "cols",
                                                                      eqOrIn |-> "=",
                                                                      exp    |-> << "{", "c", "\\in", "1", "..", "N", ":", "~", "\\E", "i", "\\in", "1", "..", "Len", "(", "queens", ")", ":"
, "Attacks", "(", "Append", "(", "queens", ",", "c", ")", ",", "i", ",", "nxtQ", ")", "}" >>,
                                                                      do     |-> <<[type   |-> "with", 
                                                                                    var    |-> "exts",
                                                                                    eqOrIn |-> "=",
                                                                                    exp    |-> << "{", "Append", "(", "queens", ",", "c", ")", ":", "c", "\\in", "cols", "}" >>,
                                                                                    do     |-> <<[type    |-> "if", 
                                                                                                  test    |-> << "(", "nxtQ", "=", "N", ")" >>,
                                                                                                  then |-> <<[type |-> "assignment",
                                                                                                              ass  |-> <<[lhs |-> [var |-> "todo", sub |-> <<  >>],
                                                                                                                          rhs |-> << "todo", "\\", "{", "queens", "}" >>]>>], 
                                                                                                             [type |-> "assignment",
                                                                                                              ass  |-> <<[lhs |-> [var |-> "sols", sub |-> <<  >>],
                                                                                                                          rhs |-> << "sols", "\\union", "exts" >>]>>]>>,
                                                                                                  else |-> <<[type |-> "assignment",
                                                                                                              ass  |-> <<[lhs |-> [var |-> "todo", sub |-> <<  >>],
                                                                                                                          rhs |-> << "(", "todo", "\\", "{", "queens", "}", ")", "\\union", "exts" >>]>>]>>]>>]>>]>>]>>], 
                                         [type |-> "assignment",
                                          ass  |-> <<[lhs |-> [var |-> "pgo_read", sub |-> << "[ "todo", "nxtQ" ]" >>],
                                                      rhs |-> << "pgo_read[ "todo", "nxtQ" ] + 1" >>], 
                                                     [lhs |-> [var |-> "pgo_read", sub |-> << "[ "sols", "nxtQ" ]" >>],
                                                      rhs |-> << "pgo_read[ "sols", "nxtQ" ] + 1" >>]>>], 
                                         [type |-> "assignment",
                                          ass  |-> <<[lhs |-> [var |-> "pgo_write", sub |-> << "[ "todo", "nxtQ" ]" >>],
                                                      rhs |-> << "pgo_write[ "todo", "nxtQ" ] + 1" >>], 
                                                     [lhs |-> [var |-> "pgo_write", sub |-> << "[ "sols", "nxtQ" ]" >>],
                                                      rhs |-> << "pgo_write[ "sols", "nxtQ" ] + 1" >>]>>]>>]>>]>>]
==========================
