name: Publish

on:
  push:
    branches: [ 'main' ]

jobs:
  publish-sonatype:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Publish'
      run: ./mill pgo.publishSonatypeCentral
      env:
        MILL_PGP_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
        MILL_PGP_SECRET_BASE64: ${{ secrets.SONATYPE_GPG }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
